typography_spectrum: 0.16827916842885315
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.042708792723715305
  lightness: 0.8207794951740652
  saturation: 0.49959763372316957
  rhythmicContrast: 0.7976710703223944
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23195087630301714
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Dave Rohr
  email: dave@davidrohrstudio.com
  url: 'http://www.davidrohrstudio.com'
logo: null
name: The David Rohr Floral Studio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Janet & James
    id: e5e8cc99-cda0-4d2d-8ed8-36b1c7e18a2d
    type: content
  - name: Chelsey & John
    id: 498c6f43-2e7c-4a63-90c0-c500308a8898
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Weddings & Events by David Rohr
description: Custom Floristry for Life's Celebrations
purpose: []
