name: The David Rohr Floral Studio
favicon: null
layout_spectrum: 0.904100336600095
typography_spectrum: 0.9053520916495472
title: "Dave Rohr's Wedding Blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#b3beba'
    - '#708181'
    - '#2b3845'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.03317344654351473
purpose: []
