typography_spectrum: 1
color:
  brandColors:
    - '#040000'
    - '#f9f9f9'
    - '#b57e49'
    - '#6a2a05'
    - '#f2c695'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Dave Rohr
  email: dave@davidrohrstudio.com
  url: 'http://www.davidrohrstudio.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a36dcbd1-1e64-4fca-8fc2-56d3d6a555e1.png
name: The David Rohr Floral Studio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Janet & James
    id: e5e8cc99-cda0-4d2d-8ed8-36b1c7e18a2d
    type: content
  - name: Chelsey & John
    id: 498c6f43-2e7c-4a63-90c0-c500308a8898
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Dave Rohr's Wedding Blog
purpose: []
