name: The David Rohr Floral Studio
favicon: null
layout_spectrum: 0.9477234
typography_spectrum: 0.45622
title: "Dave Rohr's Wedding Blog"
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ae947b'
    - '#fffcf0'
    - '#070000'
    - '#434136'
    - '#bdd18a'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.3364249
  rhythmicContrast: 1
purpose: []
