name: The David Rohr Floral Studio
favicon: null
layout_spectrum: 0.9477234
typography_spectrum: 0.9053520916495472
title: "Dave Rohr's Wedding Blog"
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8AA86'
    - '#FFFFFF'
    - '#88785C'
    - '#4B2F28'
    - '#B34B31'
  brandStrength: 0.8125
  lightness: 0.7360877
  saturation: 0.3364249
  rhythmicContrast: 0.5
purpose: []
